customhost = "employee.cizcjzl9da2u.ap-southeast-1.rds.amazonaws.com"
customuser = "kumardevops"
custompass = "bindu1987"
customdb = "employee"
custombucket = "devopsemployee"
customregion = "ap-southeast-1"
